// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/eddie023/wex-tag/ent/schema","Package":"github.com/eddie023/wex-tag/ent","Schemas":[{"name":"Transaction","config":{"Table":""}}],"Features":["privacy","entql","schema/snapshot","sql/versioned-migration"]}`
