openapi: 3.1.0
x-stoplight:
  id: wqk1o69uja3f8
info:
  title: wex-tag-transaction
  version: "1.0"
  description: "Open API specification for WEX TAG transaction API "
  contact:
    email: manish23chaulagain@gmail.com
    name: eddie023
servers:
  - url: "http://localhost:8000"
paths:
  /transaction:
    parameters: []
    post:
      summary: Create Purchase Transaction
      operationId: post-purchase-transaction
      responses:
        "201":
          description: Created
      x-stoplight:
        id: oygq6xv8rhidy
      requestBody:
        $ref: "#/components/requestBodies/CreateNewPurchaseTransaction"
  "/transaction/{transactionId}":
    parameters:
      - schema:
          type: string
        name: transactionId
        in: path
        required: true
        description: transaction id returned by post transaction API
    get:
      summary: Get Purchase Transaction
      tags: []
      responses:
        "200":
          $ref: "#/components/responses/GetPurchaseTransaction"
        "404":
          description: Transaction not found
      operationId: get-purchase-transaction
      description: |-
        Based upon purchase transactions previously submitted and stored, retrieve the stored purchase transactions converted to currencies supported by the Treasury Reporting Rates of Exchange API based
        upon the exchange rate active for the date of the purchase if available
      x-stoplight:
        id: 5ny4eesj20csi
      parameters:
        - schema:
            type: string
          in: query
          name: country
          description: country for which purchase amount should be retrived
          required: true
        - schema:
            type: string
          in: query
          name: currency
          description: currency for which purchase transaction should be converted to
          required: true
components:
  schemas:
    Transaction:
      title: Transaction
      x-stoplight:
        id: umhszkak1tyzm
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          x-stoplight:
            id: 7o695nmnkontj
          format: date-time
        amountInUSD:
          type: string
          x-stoplight:
            id: kz23a8pwhy4az
          format: double
        description:
          type: string
          x-stoplight:
            id: pdcvsif6wly5s
      required:
        - id
        - date
        - amountInUSD
        - description
  requestBodies:
    CreateNewPurchaseTransaction:
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                x-stoplight:
                  id: 5xxsk27ejj12m
                maxLength: 50
              amount:
                type: string
                x-stoplight:
                  id: 7fblc7udvwona
            required:
              - description
              - amount
  responses:
    GetPurchaseTransaction:
      description: GetPurchaseTransaction will return Purchase Transaction details based for given country and currency
      content:
        application/json:
          schema:
            type: object
            properties:
              description:
                type: string
                x-stoplight:
                  id: r540a53wjxd5v
              originalPurchasePrice:
                type: object
                x-stoplight:
                  id: rbj7xjvm02nlj
                required:
                  - currency
                  - amount
                properties:
                  currency:
                    type: string
                    x-stoplight:
                      id: pemrc8u1zbaav
                  amount:
                    type: string
                    x-stoplight:
                      id: jq8tyhvih0m98
              transaction:
                type: object
                x-stoplight:
                  id: 8zkjgb1798g9h
                required:
                  - id
                  - date
                properties:
                  id:
                    type: string
                    x-stoplight:
                      id: 765852npp64zt
                  date:
                    type: string
                    x-stoplight:
                      id: 5aaf56b9od2hz
              convertedPurchasePrice:
                type: object
                x-stoplight:
                  id: tj8b49jm2ylkn
                required:
                  - country
                  - currency
                  - exchangeRateUsed
                  - amount
                  - exchangeRateDate
                properties:
                  country:
                    type: string
                    x-stoplight:
                      id: 0w2hx15a8w047
                  currency:
                    type: string
                    x-stoplight:
                      id: q8jddcboe90jy
                  exchangeRateUsed:
                    type: string
                    x-stoplight:
                      id: y8xwiifngxv4v
                  amount:
                    type: string
                    x-stoplight:
                      id: aq21et16ka2bi
                  exchangeRateDate:
                    type: string
                    x-stoplight:
                      id: 4t1q1eatss72s
            required:
              - description
              - originalPurchasePrice
              - transaction
              - convertedPurchasePrice
