// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eddie023/wex-tag/pkg/api (interfaces: TransactionService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_transaction.go -package=mocks . TransactionService
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/eddie023/wex-tag/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CreateNewPurchase mocks base method.
func (m *MockTransactionService) CreateNewPurchase(arg0 context.Context, arg1 types.CreateNewPurchaseTransaction) (types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewPurchase", arg0, arg1)
	ret0, _ := ret[0].(types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewPurchase indicates an expected call of CreateNewPurchase.
func (mr *MockTransactionServiceMockRecorder) CreateNewPurchase(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewPurchase", reflect.TypeOf((*MockTransactionService)(nil).CreateNewPurchase), arg0, arg1)
}
