// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eddie023/wex-tag/pkg/api (interfaces: TransactionService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_transaction.go -package=mocks . TransactionService
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ent "github.com/eddie023/wex-tag/ent"
	types "github.com/eddie023/wex-tag/pkg/types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionService is a mock of TransactionService interface.
type MockTransactionService struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionServiceMockRecorder
}

// MockTransactionServiceMockRecorder is the mock recorder for MockTransactionService.
type MockTransactionServiceMockRecorder struct {
	mock *MockTransactionService
}

// NewMockTransactionService creates a new mock instance.
func NewMockTransactionService(ctrl *gomock.Controller) *MockTransactionService {
	mock := &MockTransactionService{ctrl: ctrl}
	mock.recorder = &MockTransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionService) EXPECT() *MockTransactionServiceMockRecorder {
	return m.recorder
}

// CreateNewPurchaseTransaction mocks base method.
func (m *MockTransactionService) CreateNewPurchaseTransaction(arg0 context.Context, arg1 types.CreateNewPurchaseTransaction) (types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewPurchaseTransaction", arg0, arg1)
	ret0, _ := ret[0].(types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewPurchaseTransaction indicates an expected call of CreateNewPurchaseTransaction.
func (mr *MockTransactionServiceMockRecorder) CreateNewPurchaseTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewPurchaseTransaction", reflect.TypeOf((*MockTransactionService)(nil).CreateNewPurchaseTransaction), arg0, arg1)
}

// GetPurchaseDetailsByTransactionId mocks base method.
func (m *MockTransactionService) GetPurchaseDetailsByTransactionId(arg0 context.Context, arg1 uuid.UUID) (*ent.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchaseDetailsByTransactionId", arg0, arg1)
	ret0, _ := ret[0].(*ent.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchaseDetailsByTransactionId indicates an expected call of GetPurchaseDetailsByTransactionId.
func (mr *MockTransactionServiceMockRecorder) GetPurchaseDetailsByTransactionId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchaseDetailsByTransactionId", reflect.TypeOf((*MockTransactionService)(nil).GetPurchaseDetailsByTransactionId), arg0, arg1)
}
