// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package types

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Transaction defines model for Transaction.
type Transaction struct {
	AmountInUSD string    `json:"amountInUSD"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	Id          string    `json:"id"`
}

// GetPurchaseTransaction defines model for GetPurchaseTransaction.
type GetPurchaseTransaction struct {
	Id *string `json:"id,omitempty"`
}

// CreateNewPurchaseTransaction defines model for CreateNewPurchaseTransaction.
type CreateNewPurchaseTransaction struct {
	Amount      string `json:"amount"`
	Description string `json:"description"`
}

// GetPurchaseTransactionParams defines parameters for GetPurchaseTransaction.
type GetPurchaseTransactionParams struct {
	// CountryCode country code for which purchase amount should be retrived
	CountryCode *string `form:"country-code,omitempty" json:"country-code,omitempty"`
}

// PostPurchaseTransactionJSONBody defines parameters for PostPurchaseTransaction.
type PostPurchaseTransactionJSONBody struct {
	Amount      string `json:"amount"`
	Description string `json:"description"`
}

// PostPurchaseTransactionJSONRequestBody defines body for PostPurchaseTransaction for application/json ContentType.
type PostPurchaseTransactionJSONRequestBody PostPurchaseTransactionJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetPurchaseTransaction request
	GetPurchaseTransaction(ctx context.Context, params *GetPurchaseTransactionParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostPurchaseTransactionWithBody request with any body
	PostPurchaseTransactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPurchaseTransaction(ctx context.Context, body PostPurchaseTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetPurchaseTransaction(ctx context.Context, params *GetPurchaseTransactionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPurchaseTransactionRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPurchaseTransactionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPurchaseTransactionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPurchaseTransaction(ctx context.Context, body PostPurchaseTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPurchaseTransactionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPurchaseTransactionRequest generates requests for GetPurchaseTransaction
func NewGetPurchaseTransactionRequest(server string, params *GetPurchaseTransactionParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transaction")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.CountryCode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "country-code", runtime.ParamLocationQuery, *params.CountryCode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostPurchaseTransactionRequest calls the generic PostPurchaseTransaction builder with application/json body
func NewPostPurchaseTransactionRequest(server string, body PostPurchaseTransactionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPurchaseTransactionRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPurchaseTransactionRequestWithBody generates requests for PostPurchaseTransaction with any type of body
func NewPostPurchaseTransactionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transaction")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetPurchaseTransactionWithResponse request
	GetPurchaseTransactionWithResponse(ctx context.Context, params *GetPurchaseTransactionParams, reqEditors ...RequestEditorFn) (*GetPurchaseTransactionResponse, error)

	// PostPurchaseTransactionWithBodyWithResponse request with any body
	PostPurchaseTransactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPurchaseTransactionResponse, error)

	PostPurchaseTransactionWithResponse(ctx context.Context, body PostPurchaseTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPurchaseTransactionResponse, error)
}

type GetPurchaseTransactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetPurchaseTransaction
	XML200       *GetPurchaseTransaction
}

// Status returns HTTPResponse.Status
func (r GetPurchaseTransactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPurchaseTransactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostPurchaseTransactionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostPurchaseTransactionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPurchaseTransactionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetPurchaseTransactionWithResponse request returning *GetPurchaseTransactionResponse
func (c *ClientWithResponses) GetPurchaseTransactionWithResponse(ctx context.Context, params *GetPurchaseTransactionParams, reqEditors ...RequestEditorFn) (*GetPurchaseTransactionResponse, error) {
	rsp, err := c.GetPurchaseTransaction(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPurchaseTransactionResponse(rsp)
}

// PostPurchaseTransactionWithBodyWithResponse request with arbitrary body returning *PostPurchaseTransactionResponse
func (c *ClientWithResponses) PostPurchaseTransactionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPurchaseTransactionResponse, error) {
	rsp, err := c.PostPurchaseTransactionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPurchaseTransactionResponse(rsp)
}

func (c *ClientWithResponses) PostPurchaseTransactionWithResponse(ctx context.Context, body PostPurchaseTransactionJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPurchaseTransactionResponse, error) {
	rsp, err := c.PostPurchaseTransaction(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPurchaseTransactionResponse(rsp)
}

// ParseGetPurchaseTransactionResponse parses an HTTP response from a GetPurchaseTransactionWithResponse call
func ParseGetPurchaseTransactionResponse(rsp *http.Response) (*GetPurchaseTransactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPurchaseTransactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetPurchaseTransaction
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "xml") && rsp.StatusCode == 200:
		var dest GetPurchaseTransaction
		if err := xml.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.XML200 = &dest

	}

	return response, nil
}

// ParsePostPurchaseTransactionResponse parses an HTTP response from a PostPurchaseTransactionWithResponse call
func ParsePostPurchaseTransactionResponse(rsp *http.Response) (*PostPurchaseTransactionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPurchaseTransactionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get Purchase Transaction
	// (GET /transaction)
	GetPurchaseTransaction(w http.ResponseWriter, r *http.Request, params GetPurchaseTransactionParams)
	// Create Purchase Transaction
	// (POST /transaction)
	PostPurchaseTransaction(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get Purchase Transaction
// (GET /transaction)
func (_ Unimplemented) GetPurchaseTransaction(w http.ResponseWriter, r *http.Request, params GetPurchaseTransactionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create Purchase Transaction
// (POST /transaction)
func (_ Unimplemented) PostPurchaseTransaction(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetPurchaseTransaction operation middleware
func (siw *ServerInterfaceWrapper) GetPurchaseTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPurchaseTransactionParams

	// ------------- Optional query parameter "country-code" -------------

	err = runtime.BindQueryParameter("form", true, false, "country-code", r.URL.Query(), &params.CountryCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country-code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPurchaseTransaction(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostPurchaseTransaction operation middleware
func (siw *ServerInterfaceWrapper) PostPurchaseTransaction(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPurchaseTransaction(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/transaction", wrapper.GetPurchaseTransaction)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/transaction", wrapper.PostPurchaseTransaction)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xW32/bNhD+Vwhuj04ty06a6mlp1xUBhi7oUmxA14czdRJpUyTNH5Kdwv/7QMqOf8Qe",
	"3KFPEnjkd3fffXfkN8p0Y7RC5R0tvlGLi4DOv9WlwLTwziJ4/IjdQ7CMg8NHC8oB80KraGdaeVQ+/oIx",
	"UjCIluHM9WbHODYQ/4zVBq3fwEKjQ3/KrwzSgjpvharpgC6vnNdGiponsyhpQWU7uV5cLzifQzWm6/WA",
	"luiYFWYbRQPL31HVntPiOhtchGmmKnRNu5LMdFO6jqAxeWGxpMWXAweDbbhfn6H1dIbMx2P9QWe0cn1q",
	"H9D/WK5iuMc89X73UZaN/HGEz+vg2oW6xTnOXSKcxeN29U6XeCnIa8CJqax98pWc91UDf/HpN7Wyouom",
	"uPBVOFXzS0CcaZ94biqZz1Y6geCScVA1fvqOUPytBTu77thTM5EJxWwKfJdYvVef//z1UjB+Y25BML4c",
	"LcZZAvM7ldyXl8KM6psurzoz6hrTvpTvIebgSM6pDqezOGLoWfqHCjjVCEcFOtMHpBNSEos+WEW2drK/",
	"oUQPQjoyBYclqbQltWhRkY1/wmIA0V0v9aTuo0Y7Jf3nIlXaNuBpQUsdpjKmeAnf2WIpRyZvPYTJ9EDM",
	"OzzweOVFcynkap7Nx4t6lt+qxf9WeKfD68k8qJmX4zKBnB4Xh/IQ5U4FcFD9/RBilYWXEWef4OPanw6s",
	"bvKyMyJDq2G6mVdCVXo7CIGlvdiAkLSgDSjheD5mHIKEGoT6pY6mV0w3dEAVNNEjlqXALB/TF2r7w6Ai",
	"dw/3xBlkotpMxSSfv97/TR7vPpC9nkg76S69DpdXHuorf5Bmi9b16KNXWXSpDSowghZ0/CouDagBz5PI",
	"hv5QgjWm9A6DfJskHYxWZNt7+1E5Yiy2QgcnV8SFaSO8x5KAKonz2mI5iI1jBbZIPMfN4hkoplWLNp73",
	"mrBgLSom0BEXjNFpfbpKKI8WwQW7Ip8wGoSqSWx9R3RF3m9mQeIrNeQ/KoUfD24HBbHgkUS/LSbCozGK",
	"KyLE/+cARUWgBSGh77vYpLAde+fuzcixhQY9WkeLL8eU7k+F5LzjgvGdy17dxHEdZEmm2DPYYmwAEQEW",
	"Ae1qp7AN3lWaMoO96/S4ob4eXft5lsXPzxYrWtCfhrt31fB53/BMjusBnWSTl3r57NCSj9qT33RQfXe7",
	"0DRgVz1fJwfomX7Mc+R8nsHUh5s3/SWmXTIfluFBuzN12L0NV+cz3Xs+Dv/z7bh+wd/oJQE9wnHm/er3",
	"JO/Czfz1NSieSbbcDCOHtt1qKtg4g7j3phgOpWYguXa+uM2yjMZKn8JkTVfOWQ7BwBtL1+t/AwAA///i",
	"e6dgSwsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
